### ISSUE TITLE
Segfault on close content

### ISSUE THREAD

**Issue by bslenul** [libretro/ecwolf#91]
Haven't tried on any other devices yet, but the core crashes 90% of the time on close content on Windows 10, here's the GDB output, hope it can help:
```
Thread 1 received signal SIGSEGV, Segmentation fault.
FName::GetChars (this=0x2b8b6b13f74) at ../../src/name.h:61
61              const char *GetChars() const { return NameData.NameArray[Index].Text; }
(gdb) bt full
#0  FName::GetChars (this=0x2b8b6b13f74) at ../../src/name.h:61
No locals.
#1  0x00007ff9a4a6551f in DObject::~DObject (this=0x2b8bc673630,
    __in_chrg=<optimized out>) at ../../src/dobject.cpp:265
        probe = 0x0
        type = 0x2b8b6b13f60
        probe = <optimized out>
        type = <optimized out>
#2  0x00007ff9a4a9bf90 in DCanvas::~DCanvas (this=0x2b8bc673630,
    __in_chrg=<optimized out>) at ../../src/v_video.cpp:99
        probe = <optimized out>
        prev = <optimized out>
#3  0x00007ff9a4a9c7c3 in DSimpleCanvas::~DSimpleCanvas (this=0x2b8bc673630,
    __in_chrg=<optimized out>) at ../../src/v_video.cpp:362
No locals.
#4  0x00007ff9a4b848a5 in DFrameBuffer::~DFrameBuffer (this=0x2b8bc673630,
    __in_chrg=<optimized out>) at ../../src/v_video.h:345
No locals.
#5  0x00007ff9a4b8b595 in LibretroFBBase::~LibretroFBBase (
    this=0x2b8bc673630, __in_chrg=<optimized out>)
    at ../../src/libretro/libretro.cpp:117
No locals.
#6  0x00007ff9a4b7d24a in LibretroFB<unsigned short>::~LibretroFB (
    this=0x2b8bc673630, __in_chrg=<optimized out>)
    at ../../src/libretro/libretro.cpp:146
No locals.
#7  0x00007ff9a4b85815 in LibretroFB16::~LibretroFB16 (this=0x2b8bc673630,
    __in_chrg=<optimized out>) at ../../src/libretro/libretro.cpp:243
No locals.
#8  0x00007ff9a4b857b7 in LibretroFB16::~LibretroFB16 (this=0x2b8bc673630,
    __in_chrg=<optimized out>) at ../../src/libretro/libretro.cpp:243
No locals.
#9  0x00007ff9a4aba3d6 in retro_unload_game ()
    at ../../src/libretro/libretro.cpp:422
No locals.
#10 0x00007ff7199288be in core_unload_game () at runloop.c:4963
        runloop_st = 0x7ff71aaca4e0 <runloop_state>
#11 0x00007ff719928b28 in runloop_event_deinit_core () at runloop.c:5048
        video_st = 0x7ff71ab35760 <video_driver_st>
        runloop_st = 0x7ff71aaca4e0 <runloop_state>
        settings = 0x2b8aa704b90
#12 0x00007ff719915faa in command_event (cmd=CMD_EVENT_CORE_DEINIT, data=0x0)
    at retroarch.c:2353
        hwr = 0x7ff71ab39920 <video_driver_st+16832>
        video_st = 0x7ff71ab35760 <video_driver_st>
        sys_info = 0x7ff71aaced50 <runloop_state+18544>
        boolean = false
        p_rarch = 0x7ff71aac0060 <rarch_st>
        runloop_st = 0x7ff71aaca4e0 <runloop_state>
        uico_st = 0x7ff71aae8840 <uico_driver_st>
        access_st = 0x7ff71aaca280 <access_state_st>
        menu_st = 0x7ff71ab92360 <menu_driver_state>
        video_st = 0x7ff71ab35760 <video_driver_st>
        settings = 0x2b8aa704b90
        recording_st = 0x7ff71aae88c0 <recording_state>
#13 0x00007ff71991cf52 in retroarch_ctl (state=RARCH_CTL_MAIN_DEINIT,
    data=0x0) at retroarch.c:5671
        input_st = 0x7ff71ab1e280 <input_driver_st>
        p_rarch = 0x7ff71aac0060 <rarch_st>
        runloop_st = 0x7ff71aaca4e0 <runloop_state>
#14 0x00007ff71994f9c5 in content_load (info=0xe53effb9b0,
    p_content=0x7ff71aacac58 <runloop_state+1912>)
    at tasks/task_content.c:1447
        i = 0
        success = false
        rarch_argc = 8
        rarch_argv = {0x2b8aa76e910 "retroarch", 0x2b8aa783040 "--menu",
          0x2b8aa783080 "-s",
          0x2b8aa7830c0 "G:\\msys64\\home\\B-S\\ra_build\\saves",
          0x2b8aa783120 "-S",
          0x2b8aa783160 "G:\\msys64\\home\\B-S\\ra_build\\states",
          0x2b8aa7831c0 "-c",
          0x2b8aa783200 "G:\\msys64\\home\\B-S\\ra_build\\retroarch.cfg",
          0x0 <repeats 24 times>}
        argv_copy = {0x2b8aa76e910 "retroarch", 0x2b8aa783040 "--menu",
          0x2b8aa783080 "-s",
          0x2b8aa7830c0 "G:\\msys64\\home\\B-S\\ra_build\\saves",
          0x2b8aa783120 "-S",
          0x2b8aa783160 "G:\\msys64\\home\\B-S\\ra_build\\states",
          0x2b8aa7831c0 "-c",
          0x2b8aa783200 "G:\\msys64\\home\\B-S\\ra_build\\retroarch.cfg",
          0x0 <repeats 24 times>}
        rarch_argv_ptr = 0xe53effb650
        rarch_argc_ptr = 0xe53effb758
        wrap_args = 0x2b8aa782fd0
#15 0x00007ff719950666 in task_push_start_dummy_core (
    content_info=0xe53effb9b0) at tasks/task_content.c:1966
        content_ctx = {
          name_ips = 0x2b8b6be84e0 "C:\\dosbox\\wolf3d\\ecwolf.ips",
          name_bps = 0x2b8bd3afea0 "C:\\dosbox\\wolf3d\\ecwolf.bps",
          name_ups = 0x2b8bd3afef0 "C:\\dosbox\\wolf3d\\ecwolf.ups",
          valid_extensions = 0x0, directory_cache = 0x0,
          directory_system = 0x2b8bd3aff40 "G:\\msys64\\home\\B-S\\ra_build\\system", subsystem = {data = 0x0, size = 0}, block_extract = false,
          need_fullpath = false, set_supports_no_game_enable = false,
          is_ips_pref = false, is_bps_pref = false, is_ups_pref = false,
          patch_is_blocked = false, bios_is_missing = false,
          check_firmware_before_loading = false}
        p_content = 0x7ff71aacac58 <runloop_state+1912>
        ret = true
        settings = 0x2b8aa704b90
        runloop_st = 0x7ff71aaca4e0 <runloop_state>
        sys_info = 0x7ff71aaced50 <runloop_state+18544>
        path_dir_system = 0x2b8aa733c5e "G:\\msys64\\home\\B-S\\ra_build\\system"
        check_firmware_before_loading = false
#16 0x00007ff71991528d in command_event (cmd=CMD_EVENT_UNLOAD_CORE, data=0x0)
    at retroarch.c:1951
        load_dummy_core = true
        content_info = {argv = 0x0, args = 0x0,
          environ_get = 0x7ff71994fb3f <menu_content_environment_get>,
          argc = 0}
        sys_info = 0x7ff71aaced50 <runloop_state+18544>
        contentless = false
        is_inited = true
        global = 0x7ff71aaca2a0 <global_driver_st>
        boolean = false
        p_rarch = 0x7ff71aac0060 <rarch_st>
        runloop_st = 0x7ff71aaca4e0 <runloop_state>
        uico_st = 0x7ff71aae8840 <uico_driver_st>
        access_st = 0x7ff71aaca280 <access_state_st>
        menu_st = 0x7ff71ab92360 <menu_driver_state>
        video_st = 0x7ff71ab35760 <video_driver_st>
        settings = 0x2b8aa704b90
        recording_st = 0x7ff71aae88c0 <recording_state>
#17 0x00007ff719cd5473 in generic_menu_entry_action (userdata=0x2b8abaa5750,
    entry=0xe53effecd0, i=0, action=MENU_ACTION_NOOP)
    at menu/menu_driver.c:8132
        deferred_path = 0x2b8aba9f718 "C:\\dosbox\\wolf3d\\ecwolf.exe"
        flush_target = 0x7ff71a332539 <enable_device_vibration+65335> "deferred_rpl_entry_actions"
        stack_offset = 1
        reset_navigation = true
        content_path = 0x7ff71aac2270 <rarch_st+8720> ""
        ret = 0
        menu_st = 0x7ff71ab92360 <menu_driver_state>
        menu_driver_ctx = 0x7ff71a305700 <menu_ctx_ozone>
        menu = 0x2b8aba976e0
        settings = 0x2b8aa704b90
        menu_userdata = 0x2b8abaa5750
        wraparound_enable = true
        scroll_mode = false
        scroll_accel = 0
        menu_list = 0x2b8abaeebe0
        selection_buf = 0x2b8aba92c40
        menu_stack = 0x2b8aba8e350
        selection_buf_size = 8
        cbs = 0x2b8b6da8210
        accessibility_enable = false
        accessibility_narrator_speech_speed = 5
        access_st = 0x7ff71aaca280 <access_state_st>
#18 0x00007ff719c653e0 in ozone_menu_entry_action (userdata=0x2b8abaa5750,
    entry=0xe53effecd0, i=0, action=MENU_ACTION_NOOP)
    at menu/drivers/ozone.c:7820
        new_entry = {entry_idx = 0, idx = 0, type = 0, spacing = 1073742336,
          enum_idx = 1073742400,
          path = "\000\000\000\000\b\000\000\000p▒▒>▒\000\000\000▒`▒▒▒\177\000\000▒\f\031\006▒\003\000\000\020=m▒▒\002\000\000\000\000\000\000\000\000\000\000\215^▒▒▒\177\000\000@\002\000@\001\000\000\000\001", '\000' <repeats 47 times>, "p▒▒>▒\000\000\000\020=m▒▒\002\000\000Rը▒▒\177\000\000\000\000\000\000\000\000\000\000\004\000\000\000\000\000\000\000\220\064h▒▒\002\000\000\220\064h▒▒\002\000\000\000\000\000\000▒", '\000' <repeats 11 times>, "\t▒▒^S\000\000\070\000\000\000LGVN"...,
          label = "\000\004▒▒▒\177\000\000\001\000\000\000\000\000\000\000\001", '\000' <repeats 11 times>, "\001\000\000\000\000\000P▒▒\002\000\000\000\000\000\000\000\000\000\000ܰ▒▒\177\000\000\001", '\000' <repeats 31 times>, "\001▒\230\032▒\177\000\000\000\016_▒▒\002\000\000\001\000\000\000\000\000\000\000;`Re▒\177\000\000\000ʚ;\000\000\000\000\020\021\n▒▒\002\000\000▒▒▒▒▒▒▒▒!▒▒▒\177\000\000▒\003\000\000\000\000\000\000y\005▒▒\177\000\000\065▒\230\032▒\177\000\000\001\000\000\000▒\002\000\000\000ʚ;\000\000\000\000▒[of▒\177\000\000"..., sublabel = "\000\000▒>▒\031▒\177\000\000▒\000\000\000\000\000\000\000\060▒▒>▒\000\000\000\200\002\000\000\000\000\000\000▒\000\000\000\000\000\000\000▒▒▒▒▒▒▒▒0y▒▒▒\002\000\000\220\064h▒▒\002\000\000V▒ݦ▒\177\000\000`▒Q▒▒\002\000\000s[of▒\177\000\000\000\000\000\000\000\000\000\000\220\064h▒▒\002\000\000\200\002\000\000\002\000\000\000h▒▒\032▒\177\000\000▒▒▒>▒\000\000\000▒E▒\031▒\177\000\000▒▒▒\032▒\177\000\000`▒Q▒▒\002\000\000x▒▒>▒\000\000\000`W▒\032▒\177\000\000 ▒▒>▒\000\000\000▒▒▒\031▒\177\000\000\220▒▒>▒\000\000\000\200\000\000\000▒\002"...,
          rich_label = "\000\000I▒g▒\177\000\000*", '\000' <repeats 15 times>, "\001\000\000\000▒\002\000\000\000\000\000\000\000\000\000\000+", '\000' <repeats 15 times>, "\200\025\177▒▒\002\000\000 \201▒▒▒\002", '\000' <repeats 11 times>, "\005\000\000▒\002\000\000\001\000\000\000\000\000\000\000 ▒▒>▒", '\000' <repeats 19 times>, "\004", '\000' <repeats 39 times>, "\001\000\000\000\005\000\000\000`\"▒▒▒\002\000\000\001\000\000\000▒\177\000\000▒▒▒>▒", '\000' <repeats 11 times>...,
          value = "\000\000\000 ", '\000' <repeats 23 times>, "`▒Q▒▒\002\000\000.=▒\031▒\177\000\000▒\023▒▒▒\002\000\000@\024▒▒▒\002\000\000\000\000\000\000\000\000\000\000/\000\000\000\002\000\000\000▒\024▒▒▒\002\000\000▒\024▒▒▒\002\000\000\b\025▒▒▒\002\000\000▒\023▒▒▒\002\000\000\024▒\000\000\002\000\000\000\001\000\000\000\000\000\001\000d▒▒>▒\000\000\000▒\002\000\000\000\005\000\000▒\000\000\000\000\000\000\000\003\000\000\000\000\000\000\000▒▒▒>▒\000\000\000▒_▒\031▒\177\000\000▒▒▒>▒\000\000\000▒Q▒▒▒\002\000\000▒\000\000\000\000\000\000\000`\034\201▒▒"...,
          password_value = "▒\000\000\000F\231\230\031\000\177\000\000\000\020▒▒▒\002\000\000`\034\201▒▒\002\000\000@\001\000\000\000\000\000\000▒\000\000\000▒\000\000\000o\000\000\000\000\000\000\000\200\002\000\000▒\000\000\000\000▒▒\032▒\177\000\000▒▒▒>▒", '\000' <repeats 11 times>, "▒▒▒g▒\177\000\000\000\000P▒▒\002\000\000c\000\000P", '\000' <repeats 20 times>, " \020▒▒▒\002", '\000' <repeats 26 times>, " \020▒▒▒\002\000\000\000\000P▒▒\002\000\000 \020▒▒▒\002\000\000\001", '\000' <repeats 15 times>, "\030\001▒"..., checked = 168,
          path_enabled = 184, label_enabled = 2, rich_label_enabled = false,
          value_enabled = false, sublabel_enabled = 32}
        ozone = 0x2b8abaa5750
        entry_ptr = 0xe53effecd0
        settings = 0x2b8aa704b90
        selection = 0
        new_action = MENU_ACTION_NOOP
        new_selection = 0
#19 0x00007ff719ccdb2c in menu_entry_action (entry=0xe53effecd0, i=0,
    action=MENU_ACTION_NOOP) at menu/menu_driver.c:4388
        menu_st = 0x7ff71ab92360 <menu_driver_state>
#20 0x00007ff719cd404b in generic_menu_iterate (
    menu_st=0x7ff71ab92360 <menu_driver_state>,
    p_disp=0x7ff71ab3af60 <dispgfx_st>, p_anim=0x7ff71ab3b080 <anim_st>,
    settings=0x2b8aa704b90, menu=0x2b8aba976e0, userdata=0x2b8abaa5750,
    action=MENU_ACTION_NOOP, current_time=4566176292)
    at menu/menu_driver.c:7691
        entry = {entry_idx = 0, idx = 0, type = 7, spacing = 0,
          enum_idx = MENU_ENUM_LABEL_RUN,
          path = "Run", '\000' <repeats 37 times>, "▒▒ ▒=▒\000\000$▒▒>▒\000\000\000\001\000\000\000\004\000\000\000\t\000\000\000\000\000\000\000\230>\n\200\001\000\000\000▒4▒g▒\177", '\000' <repeats 18 times>, "\200▒X▒▒\002\000\000\060▒P▒▒\002\000\000\000\000\000\000\000\000\000\000▒\002▒g▒\177\000\000▒4\000\200\001\000\000\000p▒▒>▒\000\000\000\200▒X▒▒\002\000\000\000\000\000\000\000\000\000\000\001\000\000\000▒\002\000\000tS\004#▒", '\000' <repeats 11 times>, "\002\000\004\006▒\177\000\000"...,
          label = "collection\000▒▒▒\002\000\000I▒g▒\177\000\000▒\002▒▒▒\002\000\000\000\000\000\000\000\000\000\000\001\025\004\200\001\000\000\000\177\000\000\000\001\000\000\000`ؾ▒▒\002\000\000\003\002\000\000\000\000\000\000\060\000\000\000\000\000\000\000_▒g▒\177\000\000\000\000▒▒▒\002\000\000\071▒▒>▒\000\000\000▒ؾ▒▒\002\000\000\000\000\000\000\001\000\000\000\177\000\000\000▒\002\000\000\003\002\000\000\000\000\000\000\000▒▒>▒\000\000\000\005\000\000\000\000\000\000\000\004▒▒>▒\000\000\000 \037▒▒▒\002", '\000' <repeats 18 times>, "\020\037▒▒▒\002\000\000\005\000\000\000▒\177\000\000"...,
          sublabel = "\000\000▒▒ۂ\001\000\000\000▒\023\004\200\001\000\000\000\177\000\000\000\000\000\000\000\004\b\000\000\000\000\000\000`#▒\032▒\177\000\000\006\000\000\000\000\000\000\000\005\000\000\000\000\000\000\000▒▒▒▒▒\002\000\000\200▒\032▒\177\000\000 \003▒▒▒\002\000\000P\001▒▒▒\002\000\000▒7\004▒▒\000\000\000\005\000\000\000\000\000\000\000\001\000\000\000\000\000\000\000\060\000\000\000\000\000\000\000\033\000\000\000▒\177\000\000\000\000▒>▒\000\000\000\020پ▒▒\002\000\000w\230▒g▒\177\000\000n module C:\\WIND`\025\061\032▒\177\000\000EM32\\v\000\000kan-1.dlP\000\000\000\000\000\000\000"...,
          rich_label = '\000' <repeats 18 times>, "\215▒▒f▒\177\000\000\070▒▒>▒\000\000\000\070\000\000\000_\000\000\000▒▒▒>▒\000\000\000`▒▒\031▒\177\000\000▒C▒▒▒\002\000\000\000\000\000\000▒\000\000\000▒▒\000\000▒\002\000\000`▒▒\032▒\177\000\000\000▒▒>▒\000\000\000▒Y▒\031▒\177\000\000\004\000\000\000▒\000\000\000▒▒\200?▒\177\000\000 ▒0\032▒\177\000\000\004\000\000\000\000\177\000\000▒▒▒▒\000\000\000\000\000\000\000\000▒\000\000\000`▒\032▒\177\000\000\000\000\000\000▒▒▒▒\004\000\000\000▒\002\000\000\001\000\000\000▒\177\000\000▒▒▒▒▒▒▒▒\200-▒\032▒\177"...,
          value = "\000\000\000\000\000\000\000\026\000\000\000\200▒▒>▒\000\000\000A▒▒\031▒\177\000\000▒C▒▒▒\002\000\000\000\000\000\000\004\000\000\000`\000\000@", '\000' <repeats 12 times>, " ▒\032▒\177\000\000\020\000\000\000\000\000\000\000▒▒▒>▒\000\000\000▒O▒\031▒\177\000\000▒C▒▒▒\002\000\000 ▒0\032\000\177\000\000\000\000\000\000\000\000\000\000\200▒▒>▒\000\000\000`▒\032▒\177", '\000' <repeats 18 times>, "\001\000\000\000▒\000\000\000\000\000\000\000\004\000\000\000S", '\000' <repeats 23 times>, "▒▒▒▒\000\000\000\000▒▒\000\000\000\000\000\000\000\000\000"...,
          password_value = "\000\002\000\000D▒▒\031▒\177\000\000\200▒\032▒\177\000\000S\000\000\000▒\002\000\000p▒▒>▒", '\000' <repeats 11 times>, "▒▒▒>▒\000\000\000▒▒▒\031▒\177\000\000▒C▒▒▒\002\000\000 ▒0\032▒\177\000\000\000\000\000\000\000\000\000\000▒▒▒>▒", '\000' <repeats 15 times>, "\002\000\000\000\000\000\000\000▒\177\000\000\002\000\000\000\003\000\000\000\000\000\000\000▒\177\000\000\a\000\000\000\004\000\000\000\000▒\032\001\177\000\000\001#\000\000\000\000\000\000`▒Q▒▒\002\000\000.=▒\031▒\177\000\000▒C▒▒▒\002\000\000 ▒0\032▒\177", '\000' <repeats 18 times>..., checked = false, path_enabled = true,
          label_enabled = true, rich_label_enabled = false,
          value_enabled = false, sublabel_enabled = false}
        menu_list = 0x2b8abaeebe0
        selection = 0
        menu_list_size = 8
        last_iterate_type = ITERATE_TYPE_DEFAULT
        access_st = 0x7ff71aaca280 <access_state_st>
        accessibility_enable = false
        accessibility_narrator_speech_speed = 5
        iterate_type = ITERATE_TYPE_DEFAULT
        ret = 0
        label = 0x2b8b69163a0 "deferred_rpl_entry_actions"
        list = 0x2b8aba8e350
#21 0x00007ff719cd5562 in menu_driver_iterate (
    menu_st=0x7ff71ab92360 <menu_driver_state>,
    p_disp=0x7ff71ab3af60 <dispgfx_st>, p_anim=0x7ff71ab3b080 <anim_st>,
    settings=0x2b8aa704b90, action=MENU_ACTION_NOOP, current_time=4566176292)
    at menu/menu_driver.c:8163
No locals.
#22 0x00007ff71992c5dc in runloop_check_state (error_on_init=false,
    settings=0x2b8aa704b90, current_time=4566176292) at runloop.c:6886
        action = MENU_ACTION_NOOP
        old_action = MENU_ACTION_OK
        menu_st = 0x7ff71ab92360 <menu_driver_state>
        focused = true
        trigger_input = {data = {0, 0, 0, 0, 0, 0, 0, 0}, analogs = {0, 0, 0,
            0, 0, 0, 0, 0}, analog_buttons = {0 <repeats 16 times>}}
        screensaver_timeout = 0
        old_input = {data = {9, 0, 0, 0, 0, 0, 0, 0}, analogs = {0, 0, 0, 0,
            0, 0, 0, 0}, analog_buttons = {0 <repeats 16 times>}}
        current_bits = {data = {0, 0, 0, 0, 0, 0, 0, 0}, analogs = {0, 0, 0,
            0, 0, 0, 0, 0}, analog_buttons = {0 <repeats 16 times>}}
        last_input = {data = {0, 12288, 0, 0, 0, 0, 0, 0}, analogs = {0, 0,
            0, 0, 0, 0, 0, 0}, analog_buttons = {0 <repeats 16 times>}}
        uico_st = 0x7ff71aae8840 <uico_driver_st>
        input_st = 0x7ff71ab1e280 <input_driver_st>
        video_st = 0x7ff71ab35760 <video_driver_st>
        p_disp = 0x7ff71ab3af60 <dispgfx_st>
        runloop_st = 0x7ff71aaca4e0 <runloop_state>
        old_focus = true
        cbs = 0x7ff71aacabb8 <runloop_state+1752>
        is_focused = true
        is_alive = true
        frame_count = 112
        focused = true
        rarch_is_initialized = true
        runloop_paused = false
        pause_nonactive = true
        quit_gamepad_combo = 0
        menu_st = 0x7ff71ab92360 <menu_driver_state>
        menu = 0x2b8aba976e0
        menu_toggle_gamepad_combo = 0
        menu_driver_binding_state = false
        menu_is_alive = true
        display_kb = false
        widgets_active = true
        cheevos_hardcore_active = false
#23 0x00007ff71992e856 in runloop_iterate () at runloop.c:7676
        i = 0
        dpad_mode = {ANALOG_DPAD_NONE, ANALOG_DPAD_NONE, ANALOG_DPAD_NONE,
          ANALOG_DPAD_NONE, ANALOG_DPAD_NONE, 32759, 2827091968, 696,
          446228021, 32759, 2858356336, 696, 1738779040, 32762, 1718574000,
          32762}
        input_st = 0x7ff71ab1e280 <input_driver_st>
        audio_st = 0x7ff71aaf5c00 <audio_driver_st>
        video_st = 0x7ff71ab35760 <video_driver_st>
        recording_st = 0x7ff71aae88c0 <recording_state>
        camera_st = 0x7ff71aae8860 <camera_driver_st>
        settings = 0x2b8aa704b90
        runloop_st = 0x7ff71aaca4e0 <runloop_state>
        video_frame_delay = 0
        video_frame_delay_effective = 0
        vrr_runloop_enable = false
        max_users = 5
        current_time = 4566176292
        menu_pause_libretro = true
        core_paused = true
        slowmotion_ratio = 3
        cheevos_enable = false
        audio_sync = true
        discord_st = 0x7ff71abe7180 <discord_state_st>
#24 0x00007ff719918983 in rarch_main (argc=1, argv=0x2b8a8540930, data=0x0)
    at retroarch.c:3859
        ret = 0
        app_exit = false
        p_rarch = 0x7ff71aac0060 <rarch_st>
        runloop_st = 0x7ff71aaca4e0 <runloop_state>
        video_st = 0x7ff71ab35760 <video_driver_st>
#25 0x00007ff719b63257 in SDL_main (argc=1, argv=0x2b8a8540930)
    at ui/drivers/ui_qt.cpp:4318
No locals.
#26 0x00007ff71a0e2126 in main_getcmdline ()
No symbol table info available.
#27 0x00007ff7199113ae in __tmainCRTStartup ()
    at C:/M/mingw-w64-crt-git/src/mingw-w64/mingw-w64-crt/crt/crtexe.c:329
        lock_free = <optimized out>
        fiberid = <optimized out>
        nested = <optimized out>
        lpszCommandLine = <optimized out>
        StartupInfo = {cb = 104, lpReserved = 0x2b8a8519650 "",
          lpDesktop = 0x2b8a853b680 "Winsta0\\Default",
          lpTitle = 0x2b8a853e8b0 "G:\\msys64\\home\\B-S\\ra_build\\retroarch_debug.exe", dwX = 0, dwY = 0, dwXSize = 0, dwYSize = 0, dwXCountChars = 0,
          dwYCountChars = 0, dwFillAttribute = 0, dwFlags = 0,
          wShowWindow = 0, cbReserved2 = 0, lpReserved2 = 0x0,
          hStdInput = 0xffffffffffffffff, hStdOutput = 0xffffffffffffffff,
          hStdError = 0xffffffffffffffff}
        inDoubleQuote = <optimized out>
#28 0x00007ff7199114c6 in WinMainCRTStartup ()
    at C:/M/mingw-w64-crt-git/src/mingw-w64/mingw-w64-crt/crt/crtexe.c:176
        ret = 255
```
No idea if this is related or not but I get this in the terminal on close content:
```
[INFO] [Core]: Unloading game..
Warning: 'DFrameBuffer' is freed outside the GC process.
```

**Comment by bslenul** [comment]
Can't reproduce the crash on my Linux Mint VM, tried run/close content like 50 times in a row, no problem. The "DFrameBuffer" warning does appear however (but again, no idea if this is related). Can't reproduce on my Android phone either. Might be a Windows only issue 🤔 

**edit:** A bit hard to bisect since it seems a bit random, but looks like the crashes started with b8a168d619d9d8397328c4f5eaf1bd417ab77d38, with the previous commit (ea82756bf22dc442287fa9405399a122e873dc5d) I can't trigger the crash and the "DFrameBuffer" warning doesn't appear.
